# Default configuration for GenIoT-Optimizer
# This file contains the default parameters for all components

# Data configuration
data:
  sequence_length: 100
  num_features: 8
  batch_size: 32
  num_workers: 4
  normalization: "standard"  # "standard" or "minmax"
  augmentation: true

# Generative models configuration
generative_models:
  wgan_gp:
    noise_dim: 100
    hidden_dim: 256
    lambda_gp: 10.0
    n_critic: 5
    lr_g: 0.0001
    lr_d: 0.0001
    beta1: 0.5
    beta2: 0.999
  
  vae:
    hidden_dim: 256
    latent_dim: 32
    beta: 1.0
    lr: 0.001
  
  diffusion:
    num_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    lr: 0.0001

# Network predictor configuration
network_predictor:
  hidden_dim: 256
  num_heads: 8
  num_layers: 6
  dropout: 0.1
  prediction_horizon: 10
  lr: 0.001

# Optimizer configuration
optimizer:
  num_devices: 100
  hidden_dim: 256
  lr: 3e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5
  reward_weights:
    latency: 0.3
    throughput: 0.3
    energy: 0.2
    qos: 0.2

# Digital twin configuration
digital_twin:
  num_devices: 100
  update_interval: 1.0
  simulation_speed: 1.0
  connection_probability: 0.1
  max_connections_per_device: 10

# Training pipeline configuration
training:
  phase1:
    wgan_epochs: 100
    vae_epochs: 100
    diffusion_epochs: 100
    save_interval: 10
  
  phase2:
    predictor_epochs: 50
    optimizer_timesteps: 50000
    adversarial_epochs: 20
    save_interval: 10
  
  phase3:
    online_epochs: 10
    adaptation_threshold: 0.1

# Evaluation configuration
evaluation:
  metrics:
    - "mmd"
    - "fid"
    - "inception_score"
    - "reconstruction_error"
    - "kl_divergence"
    - "anomaly_detection"
    - "temporal_consistency"
  
  thresholds:
    anomaly_ratio: 0.1
    confidence_level: 0.95

# Device types and their characteristics
device_types:
  sensor:
    packet_size_range: [32, 128]
    transmission_rate: [0.1, 1.0]
    energy_consumption: [0.5, 2.0]
    reliability: [0.9, 0.99]
    latency_sensitivity: "low"
  
  actuator:
    packet_size_range: [64, 256]
    transmission_rate: [0.5, 5.0]
    energy_consumption: [1.0, 5.0]
    reliability: [0.95, 0.999]
    latency_sensitivity: "high"
  
  camera:
    packet_size_range: [1024, 8192]
    transmission_rate: [10.0, 100.0]
    energy_consumption: [5.0, 20.0]
    reliability: [0.8, 0.95]
    latency_sensitivity: "medium"
  
  gateway:
    packet_size_range: [256, 1024]
    transmission_rate: [50.0, 500.0]
    energy_consumption: [10.0, 50.0]
    reliability: [0.99, 0.999]
    latency_sensitivity: "medium"
  
  mobile:
    packet_size_range: [128, 512]
    transmission_rate: [1.0, 10.0]
    energy_consumption: [2.0, 8.0]
    reliability: [0.85, 0.95]
    latency_sensitivity: "high"

# Traffic patterns configuration
traffic_patterns:
  burst:
    duration_range: [5, 20]
    intensity_multiplier: [2.0, 5.0]
    frequency: 0.1
    features: [0, 1, 2, 3]
  
  cyclical:
    period_range: [50, 200]
    amplitude_range: [0.5, 2.0]
    phase_offset: [0, 6.28]
    features: [0, 1, 4, 5]
  
  event_triggered:
    trigger_probability: 0.05
    surge_duration: [10, 30]
    surge_intensity: [1.5, 3.0]
    features: [0, 1, 2, 6]
  
  steady:
    baseline_range: [0.8, 1.2]
    variance: 0.1
    features: [0, 1, 4, 7]
  
  anomalous:
    anomaly_probability: 0.02
    anomaly_intensity: [3.0, 10.0]
    anomaly_duration: [3, 15]
    features: [0, 1, 2, 3, 4, 5, 6, 7]

# Use case configurations
use_cases:
  smart_city:
    devices:
      traffic_lights: 50
      sensors: 100
      cameras: 30
    optimization_weights:
      latency: 0.4
      throughput: 0.3
      energy: 0.2
      qos: 0.1
  
  manufacturing:
    devices:
      production_line: 80
      quality_sensors: 120
      actuators: 60
    optimization_weights:
      latency: 0.2
      throughput: 0.4
      energy: 0.2
      qos: 0.2
  
  smart_home:
    devices:
      thermostats: 40
      security_sensors: 60
      smart_speakers: 25
    optimization_weights:
      latency: 0.3
      throughput: 0.2
      energy: 0.4
      qos: 0.1

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "geniot_optimizer.log"
  max_size: "10MB"
  backup_count: 5

# Performance targets (from the paper)
performance_targets:
  latency_reduction: 31.4  # percentage improvement
  throughput_enhancement: 46.3  # percentage improvement
  energy_efficiency: 29.9  # percentage improvement
  anomaly_detection_f1: 91.8  # F1-score percentage
  scalability_threshold: 150  # milliseconds for 10k nodes
